name: Publish NuGet

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.x' # Update to your .NET version

    - name: Configure NuGet
      run: |
        cat > NuGet.Config << EOF
        <?xml version="1.0" encoding="utf-8"?>
        <configuration>
          <packageSources>
            <clear />
            <add key="github" value="https://nuget.pkg.github.com/Banquet-Consulting/index.json" />
            <add key="LazyMagic" value="https://nuget.pkg.github.com/LazyMagicOrg/index.json" />
            <add key="nuget.org" value="https://api.nuget.org/v3/index.json" />
          </packageSources>
          <packageSourceCredentials>
            <github>
              <add key="Username" value="USERNAME" />
              <add key="ClearTextPassword" value="${{ secrets.GITHUB_TOKEN }}" />
            </github>
            <LazyMagic>
              <add key="Username" value="USERNAME" />
              <add key="ClearTextPassword" value="${{ secrets.GITHUB_TOKEN }}" />
            </LazyMagic>
          </packageSourceCredentials>
        </configuration>
        EOF

        cat NuGet.Config

    - name: Remove MAUIApp project from solution
      run: dotnet sln BaseAppLib.sln remove "./MAUIApp/MAUIApp.csproj"

    - name: Restore dependencies
      run: dotnet restore

    - name: Build # Build solution
      run: dotnet build --no-restore

    - name: Publish
      run: |
        dotnet nuget push ../Packages/*.nupkg --source https://nuget.pkg.github.com/Banquet-Consulting/index.json --api-key ${{ secrets.GITHUB_TOKEN }}
        dotnet nuget push ../Packages/*.snupkg --source https://nuget.pkg.github.com/Banquet-Consulting/index.json --api-key ${{ secrets.GITHUB_TOKEN }}